/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Annotation */

#ifndef _Included_com_artifex_mupdf_fitz_Annotation
#define _Included_com_artifex_mupdf_fitz_Annotation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Annotation_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Annotation_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Annotation_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    getBounds
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Annotation_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    toDisplayList
 * Signature: ()Lcom/artifex/mupdf/fitz/DisplayList;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Annotation_toDisplayList
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    advance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Annotation_advance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Buffer */

#ifndef _Included_com_artifex_mupdf_fitz_Buffer
#define _Included_com_artifex_mupdf_fitz_Buffer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_Buffer_DEFAULT_BUFFER_SIZE
#define com_artifex_mupdf_fitz_Buffer_DEFAULT_BUFFER_SIZE 1024L
/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    newNativeBuffer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Buffer_newNativeBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_getLength
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readBytes
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readBytes
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    readBytesInto
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Buffer_readBytesInto
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBytesFrom
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBytesFrom
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeRune
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeRune
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    writeLines
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_writeLines
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_artifex_mupdf_fitz_Buffer
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Buffer_save
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_BufferInputStream */

#ifndef _Included_com_artifex_mupdf_fitz_BufferInputStream
#define _Included_com_artifex_mupdf_fitz_BufferInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_BufferInputStream_MAX_SKIP_BUFFER_SIZE
#define com_artifex_mupdf_fitz_BufferInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_BufferOutputStream */

#ifndef _Included_com_artifex_mupdf_fitz_BufferOutputStream
#define _Included_com_artifex_mupdf_fitz_BufferOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_ColorSpace */

#ifndef _Included_com_artifex_mupdf_fitz_ColorSpace
#define _Included_com_artifex_mupdf_fitz_ColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceGray
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceGray
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceRGB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceRGB
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceBGR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceBGR
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceCMYK
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceCMYK
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_getNumberOfComponents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Context */

#ifndef _Included_com_artifex_mupdf_fitz_Context
#define _Included_com_artifex_mupdf_fitz_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Context_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Cookie */

#ifndef _Included_com_artifex_mupdf_fitz_Cookie
#define _Included_com_artifex_mupdf_fitz_Cookie
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Cookie_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_abort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Device */

#ifndef _Included_com_artifex_mupdf_fitz_Device
#define _Included_com_artifex_mupdf_fitz_Device
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_Device_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_Device_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_Device_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_Device_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Device_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    getHints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Device_getHints
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    enableDeviceHints
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_enableDeviceHints
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    disableDeviceHints
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_disableDeviceHints
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DisplayList */

#ifndef _Included_com_artifex_mupdf_fitz_DisplayList
#define _Included_com_artifex_mupdf_fitz_DisplayList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DisplayList_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DisplayList_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    toStructuredText
 * Signature: ()Lcom/artifex/mupdf/fitz/StructuredText;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DisplayList_toStructuredText
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_DisplayList_search
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_run
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DisplayListDevice */

#ifndef _Included_com_artifex_mupdf_fitz_DisplayListDevice
#define _Included_com_artifex_mupdf_fitz_DisplayListDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_DisplayListDevice
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/DisplayList;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DisplayListDevice_newNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Document */

#ifndef _Included_com_artifex_mupdf_fitz_Document
#define _Included_com_artifex_mupdf_fitz_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    newNativeWithPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Document_newNativeWithPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    newNativeWithBuffer
 * Signature: ([BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Document_newNativeWithBuffer
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    needsPassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_needsPassword
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    authenticatePassword
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_authenticatePassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    countPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Document_countPages
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadPage
 * Signature: (I)Lcom/artifex/mupdf/fitz/Page;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_loadPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadOutline
 * Signature: ()[Lcom/artifex/mupdf/fitz/Outline;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Document_loadOutline
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    getMetaData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Document_getMetaData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    isReflowable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_isReflowable
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    layout
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_layout
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    isUnencryptedPDF
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_isUnencryptedPDF
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    toPDFDocument
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFDocument;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_toPDFDocument
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DocumentWriter */

#ifndef _Included_com_artifex_mupdf_fitz_DocumentWriter
#define _Included_com_artifex_mupdf_fitz_DocumentWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    newNativeDocumentWriter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_newNativeDocumentWriter
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    beingPage
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)Lcom/artifex/mupdf/fitz/Device;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_beingPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    endPage
 * Signature: (Lcom/artifex/mupdf/fitz/Device;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_endPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DocumentWriter
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DocumentWriter_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DrawDevice */

#ifndef _Included_com_artifex_mupdf_fitz_DrawDevice
#define _Included_com_artifex_mupdf_fitz_DrawDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_DrawDevice
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/Pixmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DrawDevice_newNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Font */

#ifndef _Included_com_artifex_mupdf_fitz_Font
#define _Included_com_artifex_mupdf_fitz_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Font_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    newNative
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Font_newNative
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Font_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    encodeCharacter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Font_encodeCharacter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    advanceGlyph
 * Signature: (IZ)F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_Font_advanceGlyph
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Image */

#ifndef _Included_com_artifex_mupdf_fitz_Image
#define _Included_com_artifex_mupdf_fitz_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Image_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Pixmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromPixmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getXResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getYResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getColorSpace
 * Signature: ()Lcom/artifex/mupdf/fitz/ColorSpace;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_getColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getNumberOfComponents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getBitsPerComponent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getBitsPerComponent
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getImageMask
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getImageMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getInterpolate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getInterpolate
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getMask
 * Signature: ()Lcom/artifex/mupdf/fitz/Image;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_getMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    toPixmap
 * Signature: ()Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_toPixmap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Link */

#ifndef _Included_com_artifex_mupdf_fitz_Link
#define _Included_com_artifex_mupdf_fitz_Link
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Matrix */

#ifndef _Included_com_artifex_mupdf_fitz_Matrix
#define _Included_com_artifex_mupdf_fitz_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_NativeDevice */

#ifndef _Included_com_artifex_mupdf_fitz_NativeDevice
#define _Included_com_artifex_mupdf_fitz_NativeDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_close
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillPath
  (JNIEnv *, jobject, jobject, jboolean, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokePath
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipPath
  (JNIEnv *, jobject, jobject, jboolean, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokePath
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillText
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokeText
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokeText
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    ignoreText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_ignoreText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillShade
 * Signature: (Lcom/artifex/mupdf/fitz/Shade;Lcom/artifex/mupdf/fitz/Matrix;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillShade
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImage
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImage
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImageMask
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipImageMask
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    popClip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_popClip
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginMask
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ZLcom/artifex/mupdf/fitz/ColorSpace;[F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginMask
  (JNIEnv *, jobject, jobject, jboolean, jobject, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endMask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginGroup
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ZZIF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginGroup
  (JNIEnv *, jobject, jobject, jboolean, jboolean, jint, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginTile
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Rect;FFLcom/artifex/mupdf/fitz/Matrix;I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginTile
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endTile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endTile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Outline */

#ifndef _Included_com_artifex_mupdf_fitz_Outline
#define _Included_com_artifex_mupdf_fitz_Outline
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_PDFDocument */

#ifndef _Included_com_artifex_mupdf_fitz_PDFDocument
#define _Included_com_artifex_mupdf_fitz_PDFDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    toDocument
 * Signature: ()Lcom/artifex/mupdf/fitz/Document;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_toDocument
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    countPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_countPages
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    findPage
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_findPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    getTrailer
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_getTrailer
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    countObjects
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_countObjects
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newNull
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newNull
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newBoolean
 * Signature: (Z)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newInteger
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newInteger
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newReal
 * Signature: (F)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newReal
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newString
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newName
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newIndirect
 * Signature: (II)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newIndirect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newArray
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newArray
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newDictionary
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newDictionary
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    createObject
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_createObject
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    deleteObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_deleteObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    newPDFGraftMap
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFGraftMap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_newPDFGraftMap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    graftObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFDocument;Lcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/PDFGraftMap;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_graftObject
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addStreamBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addStreamString
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addStreamString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addPageBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ILcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/Buffer;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addPageBuffer
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addPageString
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ILcom/artifex/mupdf/fitz/PDFObject;Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addPageString
  (JNIEnv *, jobject, jobject, jint, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    insertPage
 * Signature: (ILcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_insertPage
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    deletePage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_deletePage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addImage
 * Signature: (Lcom/artifex/mupdf/fitz/Image;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addSimpleFont
 * Signature: (Lcom/artifex/mupdf/fitz/Font;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addSimpleFont
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    addFont
 * Signature: (Lcom/artifex/mupdf/fitz/Font;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_addFont
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFDocument
 * Method:    save
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFDocument_save
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_PDFGraftMap */

#ifndef _Included_com_artifex_mupdf_fitz_PDFGraftMap
#define _Included_com_artifex_mupdf_fitz_PDFGraftMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFGraftMap
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFGraftMap_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_PDFObject */

#ifndef _Included_com_artifex_mupdf_fitz_PDFObject
#define _Included_com_artifex_mupdf_fitz_PDFObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isIndirect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isIndirect
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isNull
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isNull
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isInteger
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isInteger
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isReal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isReal
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isNumber
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isString
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isString
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isName
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isArray
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isArray
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isDictionary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isDictionary
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    isStream
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_isStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toInteger
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toByteString
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toByteString
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toIndirect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toIndirect
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    toString
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_PDFObject_toString
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    resolve
 * Signature: ()Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_resolve
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    readStream
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_readStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    readRawStream
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_PDFObject_readRawStream
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeStreamBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeStreamString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeStreamString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeRawStreamBuffer
 * Signature: (Lcom/artifex/mupdf/fitz/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeRawStreamBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    writeRawStreamString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_writeRawStreamString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    getArray
 * Signature: (I)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    getDictionary
 * Signature: (Ljava/lang/String;)Lcom/artifex/mupdf/fitz/PDFObject;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_PDFObject_getDictionary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayBoolean
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayBoolean
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayInteger
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayInteger
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putArrayPDFObject
 * Signature: (ILcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putArrayPDFObject
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringFloat
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringFloat
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryStringPDFObject
 * Signature: (Ljava/lang/String;Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryStringPDFObject
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectBoolean
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectBoolean
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectInteger
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectInteger
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectFloat
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectFloat
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectString
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectString
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    putDictionaryPDFObjectPDFObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_putDictionaryPDFObjectPDFObject
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteDictionaryString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteDictionaryString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_PDFObject
 * Method:    deleteDictionaryPDFObject
 * Signature: (Lcom/artifex/mupdf/fitz/PDFObject;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_PDFObject_deleteDictionaryPDFObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Page */

#ifndef _Included_com_artifex_mupdf_fitz_Page
#define _Included_com_artifex_mupdf_fitz_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getBounds
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    runPageContents
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_runPageContents
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getAnnotations
 * Signature: ()[Lcom/artifex/mupdf/fitz/Annotation;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_getAnnotations
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getLinks
 * Signature: ()[Lcom/artifex/mupdf/fitz/Link;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_getLinks
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toDisplayList
 * Signature: (Z)Lcom/artifex/mupdf/fitz/DisplayList;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toDisplayList
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toStructuredText
 * Signature: ()Lcom/artifex/mupdf/fitz/StructuredText;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toStructuredText
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_search
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Path */

#ifndef _Included_com_artifex_mupdf_fitz_Path
#define _Included_com_artifex_mupdf_fitz_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    cloneNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_cloneNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    currentPoint
 * Signature: ()Lcom/artifex/mupdf/fitz/Point;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_currentPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToV
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToY
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToY
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    rect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_rect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    closePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_closePath
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    transform
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_transform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/PathWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_PathWalker */

#ifndef _Included_com_artifex_mupdf_fitz_PathWalker
#define _Included_com_artifex_mupdf_fitz_PathWalker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Pixmap */

#ifndef _Included_com_artifex_mupdf_fitz_Pixmap
#define _Included_com_artifex_mupdf_fitz_Pixmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/ColorSpace;IIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Pixmap_newNative
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    clearWithValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_clearWithValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    saveAsPNG
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_saveAsPNG
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getStride
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getStride
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getNumberOfComponents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getAlpha
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getColorSpace
 * Signature: ()Lcom/artifex/mupdf/fitz/ColorSpace;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getSamples
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getSamples
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getSample
 * Signature: (III)B
 */
JNIEXPORT jbyte JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getSample
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getPixels
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getPixels
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getXResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getYResolution
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Point */

#ifndef _Included_com_artifex_mupdf_fitz_Point
#define _Included_com_artifex_mupdf_fitz_Point
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Rect */

#ifndef _Included_com_artifex_mupdf_fitz_Rect
#define _Included_com_artifex_mupdf_fitz_Rect
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_RectI */

#ifndef _Included_com_artifex_mupdf_fitz_RectI
#define _Included_com_artifex_mupdf_fitz_RectI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Shade */

#ifndef _Included_com_artifex_mupdf_fitz_Shade
#define _Included_com_artifex_mupdf_fitz_Shade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Shade
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Shade_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_StrokeState */

#ifndef _Included_com_artifex_mupdf_fitz_StrokeState
#define _Included_com_artifex_mupdf_fitz_StrokeState
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_BUTT
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_BUTT 0L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_ROUND
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_SQUARE
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_SQUARE 2L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_TRIANGLE
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_TRIANGLE 3L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER 0L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_ROUND
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_BEVEL
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_BEVEL 2L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER_XPS
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER_XPS 3L
/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StrokeState_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    newNative
 * Signature: (IIIIFFF[F)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_StrokeState_newNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    adjustRectForStroke
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StrokeState_adjustRectForStroke
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getStartCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getStartCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getEndCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getEndCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineJoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineJoin
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getMiterLimit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getMiterLimit
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashPhase
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashPhase
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashes
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_StructuredText */

#ifndef _Included_com_artifex_mupdf_fitz_StructuredText
#define _Included_com_artifex_mupdf_fitz_StructuredText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StructuredText_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    search
 * Signature: (Ljava/lang/String;)[Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_StructuredText_search
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    highlight
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)[Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_StructuredText_highlight
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StructuredText
 * Method:    copy
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_StructuredText_copy
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Text */

#ifndef _Included_com_artifex_mupdf_fitz_Text
#define _Included_com_artifex_mupdf_fitz_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Text_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    cloneNative
 * Signature: (Lcom/artifex/mupdf/fitz/Text;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Text_cloneNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showGlyph
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;IIZ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showGlyph
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showString
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showString
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Text_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/TextWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_TextWalker */

#ifndef _Included_com_artifex_mupdf_fitz_TextWalker
#define _Included_com_artifex_mupdf_fitz_TextWalker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_TryLaterException */

#ifndef _Included_com_artifex_mupdf_fitz_TryLaterException
#define _Included_com_artifex_mupdf_fitz_TryLaterException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_TryLaterException_serialVersionUID
#define com_artifex_mupdf_fitz_TryLaterException_serialVersionUID -3042686055658047285LL
#undef com_artifex_mupdf_fitz_TryLaterException_serialVersionUID
#define com_artifex_mupdf_fitz_TryLaterException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
