/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_mupdf_fitz_Annotation */

#ifndef _Included_com_artifex_mupdf_fitz_Annotation
#define _Included_com_artifex_mupdf_fitz_Annotation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Annotation_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Annotation_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Annotation
 * Method:    advance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Annotation_advance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_ColorSpace */

#ifndef _Included_com_artifex_mupdf_fitz_ColorSpace
#define _Included_com_artifex_mupdf_fitz_ColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceGray
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceGray
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceRGB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceRGB
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceBGR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceBGR
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    nativeDeviceCMYK
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_nativeDeviceCMYK
  (JNIEnv *, jclass);

/*
 * Class:     com_artifex_mupdf_fitz_ColorSpace
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_ColorSpace_getNumberOfComponents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Context */

#ifndef _Included_com_artifex_mupdf_fitz_Context
#define _Included_com_artifex_mupdf_fitz_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Context
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Context_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Cookie */

#ifndef _Included_com_artifex_mupdf_fitz_Cookie
#define _Included_com_artifex_mupdf_fitz_Cookie
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Cookie_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Cookie
 * Method:    abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Cookie_abort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Device */

#ifndef _Included_com_artifex_mupdf_fitz_Device
#define _Included_com_artifex_mupdf_fitz_Device
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_Device_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_Device_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_Device_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_Device_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_Device_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_Device_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_Device_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Device_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    getHints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Device_getHints
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    enableDeviceHints
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_enableDeviceHints
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Device
 * Method:    disableDeviceHints
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Device_disableDeviceHints
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DisplayList */

#ifndef _Included_com_artifex_mupdf_fitz_DisplayList
#define _Included_com_artifex_mupdf_fitz_DisplayList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DisplayList_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_DisplayList
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_DisplayList_run
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DisplayListDevice */

#ifndef _Included_com_artifex_mupdf_fitz_DisplayListDevice
#define _Included_com_artifex_mupdf_fitz_DisplayListDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_DisplayListDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_DisplayListDevice
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/DisplayList;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DisplayListDevice_newNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Document */

#ifndef _Included_com_artifex_mupdf_fitz_Document
#define _Included_com_artifex_mupdf_fitz_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Document_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    newNativeWithPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Document_newNativeWithPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    newNativeWithBuffer
 * Signature: ([BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Document_newNativeWithBuffer
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    needsPassword
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_needsPassword
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    authenticatePassword
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_authenticatePassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    countPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Document_countPages
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadPage
 * Signature: (I)Lcom/artifex/mupdf/fitz/Page;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_loadPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    loadOutline
 * Signature: ()Lcom/artifex/mupdf/fitz/Outline;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Document_loadOutline
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    getMetaData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Document_getMetaData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Document
 * Method:    isUnencryptedPDF
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Document_isUnencryptedPDF
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_DrawDevice */

#ifndef _Included_com_artifex_mupdf_fitz_DrawDevice
#define _Included_com_artifex_mupdf_fitz_DrawDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_DrawDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_DrawDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_DrawDevice
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/Pixmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_DrawDevice_newNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Font */

#ifndef _Included_com_artifex_mupdf_fitz_Font
#define _Included_com_artifex_mupdf_fitz_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Font_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    newNative
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Font_newNative
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_artifex_mupdf_fitz_Font_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    encodeCharacter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Font_encodeCharacter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Font
 * Method:    advanceGlyph
 * Signature: (IZ)F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_Font_advanceGlyph
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Image */

#ifndef _Included_com_artifex_mupdf_fitz_Image
#define _Included_com_artifex_mupdf_fitz_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Image_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Pixmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromPixmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    newNativeFromFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Image_newNativeFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getXResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getYResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getNumberOfComponents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getBitsPerComponent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Image_getBitsPerComponent
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getImageMask
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getImageMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getInterpolate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Image_getInterpolate
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    getMask
 * Signature: ()Lcom/artifex/mupdf/fitz/Image;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_getMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Image
 * Method:    toPixmap
 * Signature: ()Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Image_toPixmap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Link */

#ifndef _Included_com_artifex_mupdf_fitz_Link
#define _Included_com_artifex_mupdf_fitz_Link
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Link
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Link_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Link
 * Method:    getNext
 * Signature: ()Lcom/artifex/mupdf/fitz/Link;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Link_getNext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Matrix */

#ifndef _Included_com_artifex_mupdf_fitz_Matrix
#define _Included_com_artifex_mupdf_fitz_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_NativeDevice */

#ifndef _Included_com_artifex_mupdf_fitz_NativeDevice
#define _Included_com_artifex_mupdf_fitz_NativeDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MASK
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MASK 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_COLOR
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_COLOR 2L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_UNCACHEABLE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_UNCACHEABLE 4L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_FILLCOLOR_UNDEFINED 8L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STROKECOLOR_UNDEFINED 16L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_STARTCAP_UNDEFINED 32L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_DASHCAP_UNDEFINED 64L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_ENDCAP_UNDEFINED 128L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEJOIN_UNDEFINED 256L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_MITERLIMIT_UNDEFINED 512L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_DEVFLAG_LINEWIDTH_UNDEFINED 1024L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_NORMAL
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_NORMAL 0L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MULTIPLY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MULTIPLY 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SCREEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SCREEN 2L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_OVERLAY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_OVERLAY 3L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DARKEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DARKEN 4L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LIGHTEN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LIGHTEN 5L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_DODGE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_DODGE 6L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_BURN
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR_BURN 7L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HARD_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HARD_LIGHT 8L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SOFT_LIGHT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SOFT_LIGHT 9L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DIFFERENCE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_DIFFERENCE 10L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_EXCLUSION
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_EXCLUSION 11L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HUE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_HUE 12L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SATURATION
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_SATURATION 13L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_COLOR 14L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LUMINOSITY
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_LUMINOSITY 15L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MODEMASK
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_MODEMASK 15L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_ISOLATED
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_ISOLATED 16L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_KNOCKOUT
#define com_artifex_mupdf_fitz_NativeDevice_FZ_BLEND_KNOCKOUT 32L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_IMAGE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_IMAGE 1L
#undef com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_SHADE
#define com_artifex_mupdf_fitz_NativeDevice_FZ_IGNORE_SHADE 2L
/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_close
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillPath
  (JNIEnv *, jobject, jobject, jboolean, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokePath
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipPath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;ZLcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipPath
  (JNIEnv *, jobject, jobject, jboolean, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokePath
 * Signature: (Lcom/artifex/mupdf/fitz/Path;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokePath
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillText
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    strokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_strokeText
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipStrokeText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipStrokeText
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    ignoreText
 * Signature: (Lcom/artifex/mupdf/fitz/Text;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_ignoreText
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillShade
 * Signature: (Lcom/artifex/mupdf/fitz/Shade;Lcom/artifex/mupdf/fitz/Matrix;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillShade
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImage
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImage
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    fillImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;[FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_fillImageMask
  (JNIEnv *, jobject, jobject, jobject, jobject, jfloatArray, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    clipImageMask
 * Signature: (Lcom/artifex/mupdf/fitz/Image;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_clipImageMask
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    popClip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_popClip
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginMask
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ZLcom/artifex/mupdf/fitz/ColorSpace;[F)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginMask
  (JNIEnv *, jobject, jobject, jboolean, jobject, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endMask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endMask
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginGroup
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;ZZIF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginGroup
  (JNIEnv *, jobject, jobject, jboolean, jboolean, jint, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endGroup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    beginTile
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Rect;FFLcom/artifex/mupdf/fitz/Matrix;I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_beginTile
  (JNIEnv *, jobject, jobject, jobject, jfloat, jfloat, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_NativeDevice
 * Method:    endTile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_NativeDevice_endTile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Outline */

#ifndef _Included_com_artifex_mupdf_fitz_Outline
#define _Included_com_artifex_mupdf_fitz_Outline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Outline
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Outline_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Page */

#ifndef _Included_com_artifex_mupdf_fitz_Page
#define _Included_com_artifex_mupdf_fitz_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getBounds
 * Signature: ()Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_getBounds
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    toPixmap
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/ColorSpace;Z)Lcom/artifex/mupdf/fitz/Pixmap;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Page_toPixmap
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    run
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_run
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    runPageContents
 * Signature: (Lcom/artifex/mupdf/fitz/Device;Lcom/artifex/mupdf/fitz/Matrix;Lcom/artifex/mupdf/fitz/Cookie;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Page_runPageContents
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getAnnotations
 * Signature: ()[Lcom/artifex/mupdf/fitz/Annotation;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_getAnnotations
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Page
 * Method:    getLinks
 * Signature: ()[Lcom/artifex/mupdf/fitz/Link;
 */
JNIEXPORT jobjectArray JNICALL Java_com_artifex_mupdf_fitz_Page_getLinks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Path */

#ifndef _Included_com_artifex_mupdf_fitz_Path
#define _Included_com_artifex_mupdf_fitz_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    cloneNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Path_cloneNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    currentPoint
 * Signature: ()Lcom/artifex/mupdf/fitz/Point;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_currentPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToV
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    curveToY
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_curveToY
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    closePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_closePath
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    transform
 * Signature: (Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_transform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Path_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Path
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/PathWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Path_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_PathWalker */

#ifndef _Included_com_artifex_mupdf_fitz_PathWalker
#define _Included_com_artifex_mupdf_fitz_PathWalker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Pixmap */

#ifndef _Included_com_artifex_mupdf_fitz_Pixmap
#define _Included_com_artifex_mupdf_fitz_Pixmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    newNative
 * Signature: (Lcom/artifex/mupdf/fitz/ColorSpace;IIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Pixmap_newNative
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    clearWithValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_clearWithValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    saveAsPNG
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Pixmap_saveAsPNG
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getStride
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getStride
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getNumberOfComponents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getNumberOfComponents
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getAlpha
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getColorSpace
 * Signature: ()Lcom/artifex/mupdf/fitz/ColorSpace;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getSamples
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getSamples
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Pixmap
 * Method:    getPixels
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_artifex_mupdf_fitz_Pixmap_getPixels
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Point */

#ifndef _Included_com_artifex_mupdf_fitz_Point
#define _Included_com_artifex_mupdf_fitz_Point
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Rect */

#ifndef _Included_com_artifex_mupdf_fitz_Rect
#define _Included_com_artifex_mupdf_fitz_Rect
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_RectI */

#ifndef _Included_com_artifex_mupdf_fitz_RectI
#define _Included_com_artifex_mupdf_fitz_RectI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Shade */

#ifndef _Included_com_artifex_mupdf_fitz_Shade
#define _Included_com_artifex_mupdf_fitz_Shade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Shade
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Shade_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_StrokeState */

#ifndef _Included_com_artifex_mupdf_fitz_StrokeState
#define _Included_com_artifex_mupdf_fitz_StrokeState
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_BUTT
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_BUTT 0L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_ROUND
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_SQUARE
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_SQUARE 2L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_TRIANGLE
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINECAP_TRIANGLE 3L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER 0L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_ROUND
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_ROUND 1L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_BEVEL
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_BEVEL 2L
#undef com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER_XPS
#define com_artifex_mupdf_fitz_StrokeState_FZ_LINEJOIN_MITER_XPS 3L
/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StrokeState_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    newNative
 * Signature: (IIIIFFF[F)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_StrokeState_newNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    adjustRectForStroke
 * Signature: (Lcom/artifex/mupdf/fitz/Rect;Lcom/artifex/mupdf/fitz/Matrix;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_StrokeState_adjustRectForStroke
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getStartCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getStartCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getEndCap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getEndCap
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineJoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineJoin
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getMiterLimit
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getMiterLimit
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashPhase
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashPhase
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_StrokeState
 * Method:    getDashes
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_artifex_mupdf_fitz_StrokeState_getDashes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_Text */

#ifndef _Included_com_artifex_mupdf_fitz_Text
#define _Included_com_artifex_mupdf_fitz_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    newNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Text_newNative
  (JNIEnv *, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    cloneNative
 * Signature: (Lcom/artifex/mupdf/fitz/Text;)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_mupdf_fitz_Text_cloneNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showGlyph
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;IIZ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showGlyph
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    showString
 * Signature: (Lcom/artifex/mupdf/fitz/Font;Lcom/artifex/mupdf/fitz/Matrix;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_showString
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    getBounds
 * Signature: (Lcom/artifex/mupdf/fitz/StrokeState;Lcom/artifex/mupdf/fitz/Matrix;)Lcom/artifex/mupdf/fitz/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_artifex_mupdf_fitz_Text_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_artifex_mupdf_fitz_Text
 * Method:    walk
 * Signature: (Lcom/artifex/mupdf/fitz/TextWalker;)V
 */
JNIEXPORT void JNICALL Java_com_artifex_mupdf_fitz_Text_walk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_TextWalker */

#ifndef _Included_com_artifex_mupdf_fitz_TextWalker
#define _Included_com_artifex_mupdf_fitz_TextWalker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_artifex_mupdf_fitz_TryLaterException */

#ifndef _Included_com_artifex_mupdf_fitz_TryLaterException
#define _Included_com_artifex_mupdf_fitz_TryLaterException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_mupdf_fitz_TryLaterException_serialVersionUID
#define com_artifex_mupdf_fitz_TryLaterException_serialVersionUID -3042686055658047285LL
#undef com_artifex_mupdf_fitz_TryLaterException_serialVersionUID
#define com_artifex_mupdf_fitz_TryLaterException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
