default:
	@echo INSTALLING NODE DEPS
	@npm install -s

debug:
	bash tools/build.sh debug

memento:
	bash tools/build.sh memento

release:
	bash tools/build.sh release

clean:
	rm -rf dist
	rm -rf ../../build/wasm
