// Copyright (C) 2004-2021 Artifex Software, Inc.
//
// This file is part of MuPDF.
//
// MuPDF is free software: you can redistribute it and/or modify it under the
// terms of the GNU Affero General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// MuPDF is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
// details.
//
// You should have received a copy of the GNU Affero General Public License
// along with MuPDF. If not, see <https://www.gnu.org/licenses/agpl-3.0.en.html>
//
// Alternative licensing terms are available from the licensor.
// For commercial licensing, see <https://www.artifex.com/> or contact
// Artifex Software, Inc., 1305 Grant Avenue - Suite 200, Novato,
// CA 94945, U.S.A., +1(415)492-9861, for further information.

#ifndef TOFU_BASE14
FONT (urw, NimbusMonoPS_Regular_cff, "Courier", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, NimbusMonoPS_Regular_cff, "Nimbus Mono", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (urw, NimbusMonoPS_Italic_cff, "Courier-Oblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusMonoPS_Italic_cff, "Nimbus Mono Oblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
FONT (urw, NimbusMonoPS_Bold_cff, "Courier-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusMonoPS_Bold_cff, "Nimbus Mono Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
FONT (urw, NimbusMonoPS_BoldItalic_cff, "Courier-BoldOblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusMonoPS_BoldItalic_cff, "Nimbus Mono-BoldOblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
FONT (urw, NimbusSans_Regular_cff, "Helvetica", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, NimbusSans_Regular_cff, "Arial", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, NimbusSans_Regular_cff, "Nimbus Sans", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (urw, NimbusSans_Italic_cff, "Helvetica-Oblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusSans_Italic_cff, "Arial-Oblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusSans_Italic_cff, "Nimbus Sans-Oblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
FONT (urw, NimbusSans_Bold_cff, "Helvetica-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusSans_Bold_cff, "Arial-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusSans_Bold_cff, "Nimbus Sans-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
FONT (urw, NimbusSans_BoldItalic_cff, "Helvetica-BoldOblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusSans_BoldItalic_cff, "Arial-BoldOblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusSans_BoldItalic_cff, "Nimbus Sans-BoldOblique", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
FONT (urw, NimbusRoman_Regular_cff, "Times-Roman", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, NimbusRoman_Regular_cff, "Times New Roman", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, NimbusRoman_Regular_cff, "Nimbus Roman", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (urw, NimbusRoman_Italic_cff, "Times-Italic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusRoman_Italic_cff, "Times Roman-Italic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusRoman_Italic_cff, "Times New Roman-Italic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
ALIAS(urw, NimbusRoman_Italic_cff, "Nimbus-Italic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
FONT (urw, NimbusRoman_Bold_cff, "Times-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusRoman_Bold_cff, "Times Roman-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusRoman_Bold_cff, "Times New Roman-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
ALIAS(urw, NimbusRoman_Bold_cff, "Nimbus-Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
FONT (urw, NimbusRoman_BoldItalic_cff, "Times-BoldItalic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusRoman_BoldItalic_cff, "Times Roman-BoldItalic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusRoman_BoldItalic_cff, "Times New Roman-BoldItalic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
ALIAS(urw, NimbusRoman_BoldItalic_cff, "Nimbus-BoldItalic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
FONT (urw, StandardSymbolsPS_cff, "Symbol", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, StandardSymbolsPS_cff, "Standard Symbols PS", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (urw, Dingbats_cff, "ZapfDingbats", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(urw, Dingbats_cff, "Dingbats", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
#endif

#ifndef TOFU_SIL
FONT (sil, CharisSIL_cff, "Charis SIL", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (sil, CharisSIL_Italic_cff, "Charis SIL Italic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, ITALIC)
FONT (sil, CharisSIL_Bold_cff, "Charis SIL Bold", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD)
FONT (sil, CharisSIL_BoldItalic_cff, "Charis SIL BoldItalic", ANY_SCRIPT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, BOLD|ITALIC)
#endif

#ifndef TOFU_NOTO
FONT (noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_LATIN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_GREEK, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_CYRILLIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_COMMON, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_INHERITED, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoSerif_Regular_otf, "Noto Serif Regular", UCDN_SCRIPT_UNKNOWN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)

FONT (noto, NotoNastaliqUrdu_Regular_otf, "Noto Nastaliq Urdu Regular", UCDN_SCRIPT_ARABIC, FZ_LANG_ur, ANY_ORDER, NO_SUBFONT, REGULAR)
ALIAS(noto, NotoNastaliqUrdu_Regular_otf, "Noto Nastaliq Urdu Regular", UCDN_SCRIPT_ARABIC, FZ_LANG_urd, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoNaskhArabic_Regular_otf,  "Noto Nastaliq Urdu Regular", UCDN_SCRIPT_ARABIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)

FONT (noto, NotoSansAdlam_Regular_otf, "Noto Sans Adlam Regular", UCDN_SCRIPT_ADLAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifAhom_Regular_otf, "Noto Serif Ahom Regular", UCDN_SCRIPT_AHOM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansAnatolianHieroglyphs_Regular_otf, "Noto Sans Anatolian Hieroglyphs Regular", UCDN_SCRIPT_ANATOLIAN_HIEROGLYPHS, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifArmenian_Regular_otf, "Noto Serif Armenian Regular", UCDN_SCRIPT_ARMENIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansAvestan_Regular_otf, "Noto Sans Avestan Regular", UCDN_SCRIPT_AVESTAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifBalinese_Regular_otf, "Noto Serif Balinese Regular", UCDN_SCRIPT_BALINESE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBamum_Regular_otf, "Noto Sans Bamum Regular", UCDN_SCRIPT_BAMUM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBassaVah_Regular_otf, "Noto Sans Bassa Vah Regular", UCDN_SCRIPT_BASSA_VAH, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBatak_Regular_otf, "Noto Sans Batak Regular", UCDN_SCRIPT_BATAK, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifBengali_Regular_otf, "Noto Serif Bengali Regular", UCDN_SCRIPT_BENGALI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBhaiksuki_Regular_otf, "Noto Sans Bhaiksuki Regular", UCDN_SCRIPT_BHAIKSUKI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBrahmi_Regular_otf, "Noto Sans Brahmi Regular", UCDN_SCRIPT_BRAHMI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBuginese_Regular_otf, "Noto Sans Buginese Regular", UCDN_SCRIPT_BUGINESE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansBuhid_Regular_otf, "Noto Sans Buhid Regular", UCDN_SCRIPT_BUHID, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCanadianAboriginal_Regular_otf, "Noto Sans Canadian Aboriginal Regular", UCDN_SCRIPT_CANADIAN_ABORIGINAL, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCarian_Regular_otf, "Noto Sans Carian Regular", UCDN_SCRIPT_CARIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCaucasianAlbanian_Regular_otf, "Noto Sans Caucasian Albanian Regular", UCDN_SCRIPT_CAUCASIAN_ALBANIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansChakma_Regular_otf, "Noto Sans Chakma Regular", UCDN_SCRIPT_CHAKMA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCham_Regular_otf, "Noto Sans Cham Regular", UCDN_SCRIPT_CHAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCherokee_Regular_otf, "Noto Sans Cherokee Regular", UCDN_SCRIPT_CHEROKEE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCoptic_Regular_otf, "Noto Sans Coptic Regular", UCDN_SCRIPT_COPTIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCuneiform_Regular_otf, "Noto Sans Cuneiform Regular", UCDN_SCRIPT_CUNEIFORM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansCypriot_Regular_otf, "Noto Sans Cypriot Regular", UCDN_SCRIPT_CYPRIOT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansDeseret_Regular_otf, "Noto Sans Deseret Regular", UCDN_SCRIPT_DESERET, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifDevanagari_Regular_otf, "Noto Serif Devanagari Regular", UCDN_SCRIPT_DEVANAGARI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifDogra_Regular_otf, "Noto Serif Dogra Regular", UCDN_SCRIPT_DOGRA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansDuployan_Regular_otf, "Noto Sans Duployan Regular", UCDN_SCRIPT_DUPLOYAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansEgyptianHieroglyphs_Regular_otf, "Noto Sans Egyptian Hieroglyphs Regular", UCDN_SCRIPT_EGYPTIAN_HIEROGLYPHS, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansElbasan_Regular_otf, "Noto Sans Elbasan Regular", UCDN_SCRIPT_ELBASAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansElymaic_Regular_otf, "Noto Sans Elymaic Regular", UCDN_SCRIPT_ELYMAIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifEthiopic_Regular_otf, "Noto Serif Ethiopic Regular", UCDN_SCRIPT_ETHIOPIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifGeorgian_Regular_otf, "Noto Serif Georgian Regular", UCDN_SCRIPT_GEORGIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansGlagolitic_Regular_otf, "Noto Sans Glagolitic Regular", UCDN_SCRIPT_GLAGOLITIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansGothic_Regular_otf, "Noto Sans Gothic Regular", UCDN_SCRIPT_GOTHIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifGrantha_Regular_otf, "Noto Serif Grantha Regular", UCDN_SCRIPT_GRANTHA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifGujarati_Regular_otf, "Noto Serif Gujarati Regular", UCDN_SCRIPT_GUJARATI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansGunjalaGondi_Regular_otf, "Noto Sans Gunjala Gondi Regular", UCDN_SCRIPT_GUNJALA_GONDI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifGurmukhi_Regular_otf, "Noto Serif Gurmukhi Regular", UCDN_SCRIPT_GURMUKHI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansHanifiRohingya_Regular_otf, "Noto Sans Hanifi Rohingya Regular", UCDN_SCRIPT_HANIFI_ROHINGYA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansHanunoo_Regular_otf, "Noto Sans Hanunoo Regular", UCDN_SCRIPT_HANUNOO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansHatran_Regular_otf, "Noto Sans Hatran Regular", UCDN_SCRIPT_HATRAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifHebrew_Regular_otf, "Noto Serif Hebrew Regular", UCDN_SCRIPT_HEBREW, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansImperialAramaic_Regular_otf, "Noto Sans Imperial Aramaic Regular", UCDN_SCRIPT_IMPERIAL_ARAMAIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansInscriptionalPahlavi_Regular_otf, "Noto Sans Inscriptional Pahlavi Regular", UCDN_SCRIPT_INSCRIPTIONAL_PAHLAVI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansInscriptionalParthian_Regular_otf, "Noto Sans Inscriptional Parthian Regular", UCDN_SCRIPT_INSCRIPTIONAL_PARTHIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansJavanese_Regular_otf, "Noto Sans Javanese Regular", UCDN_SCRIPT_JAVANESE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansKaithi_Regular_otf, "Noto Sans Kaithi Regular", UCDN_SCRIPT_KAITHI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifKannada_Regular_otf, "Noto Serif Kannada Regular", UCDN_SCRIPT_KANNADA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansKayahLi_Regular_otf, "Noto Sans Kayah Li Regular", UCDN_SCRIPT_KAYAH_LI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansKharoshthi_Regular_otf, "Noto Sans Kharoshthi Regular", UCDN_SCRIPT_KHAROSHTHI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifKhmer_Regular_otf, "Noto Serif Khmer Regular", UCDN_SCRIPT_KHMER, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifKhojki_Regular_otf, "Noto Serif Khojki Regular", UCDN_SCRIPT_KHOJKI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansKhudawadi_Regular_otf, "Noto Sans Khudawadi Regular", UCDN_SCRIPT_KHUDAWADI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifLao_Regular_otf, "Noto Serif Lao Regular", UCDN_SCRIPT_LAO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLepcha_Regular_otf, "Noto Sans Lepcha Regular", UCDN_SCRIPT_LEPCHA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLimbu_Regular_otf, "Noto Sans Limbu Regular", UCDN_SCRIPT_LIMBU, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLinearA_Regular_otf, "Noto Sans LinearA Regular", UCDN_SCRIPT_LINEAR_A, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLinearB_Regular_otf, "Noto Sans LinearB Regular", UCDN_SCRIPT_LINEAR_B, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLisu_Regular_otf, "Noto Sans Lisu Regular", UCDN_SCRIPT_LISU, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLycian_Regular_otf, "Noto Sans Lycian Regular", UCDN_SCRIPT_LYCIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansLydian_Regular_otf, "Noto Sans Lydian Regular", UCDN_SCRIPT_LYDIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMahajani_Regular_otf, "Noto Sans Mahajani Regular", UCDN_SCRIPT_MAHAJANI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifMalayalam_Regular_otf, "Noto Serif Malayalam Regular", UCDN_SCRIPT_MALAYALAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMandaic_Regular_otf, "Noto Sans Mandaic Regular", UCDN_SCRIPT_MANDAIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansManichaean_Regular_otf, "Noto Sans Manichaean Regular", UCDN_SCRIPT_MANICHAEAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMarchen_Regular_otf, "Noto Sans Marchen Regular", UCDN_SCRIPT_MARCHEN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMasaramGondi_Regular_otf, "Noto Sans Masaram Gondi Regular", UCDN_SCRIPT_MASARAM_GONDI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMedefaidrin_Regular_otf, "Noto Sans Medefaidrin Regular", UCDN_SCRIPT_MEDEFAIDRIN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMeeteiMayek_Regular_otf, "Noto Sans MeeteiMayek Regular", UCDN_SCRIPT_MEETEI_MAYEK, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMendeKikakui_Regular_otf, "Noto Sans MendeKikakui Regular", UCDN_SCRIPT_MENDE_KIKAKUI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMeroitic_Regular_otf, "Noto Sans Meroitic Regular", UCDN_SCRIPT_MEROITIC_CURSIVE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMeroitic_Regular_otf, "Noto Sans Meroitic Regular", UCDN_SCRIPT_MEROITIC_HIEROGLYPHS, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMiao_Regular_otf, "Noto Sans Miao Regular", UCDN_SCRIPT_MIAO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansModi_Regular_otf, "Noto Sans Modi Regular", UCDN_SCRIPT_MODI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMongolian_Regular_otf, "Noto Sans Mongolian Regular", UCDN_SCRIPT_MONGOLIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMro_Regular_otf, "Noto Sans Mro Regular", UCDN_SCRIPT_MRO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansMultani_Regular_otf, "Noto Sans Multani Regular", UCDN_SCRIPT_MULTANI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifMyanmar_Regular_otf, "Noto Serif Myanmar Regular", UCDN_SCRIPT_MYANMAR, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansNabataean_Regular_otf, "Noto Sans Nabataean Regular", UCDN_SCRIPT_NABATAEAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansNewa_Regular_otf, "Noto Sans Newa Regular", UCDN_SCRIPT_NEWA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansNewTaiLue_Regular_otf, "Noto Sans New Tai Lue Regular", UCDN_SCRIPT_NEW_TAI_LUE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansNKo_Regular_otf, "Noto Sans N Ko Regular", UCDN_SCRIPT_NKO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansNushu_Regular_otf, "Noto Sans Nushu Regular", UCDN_SCRIPT_NUSHU, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifNyiakengPuachueHmong_Regular_otf, "Noto Serif Nyiakeng Puachue Hmong Regular", UCDN_SCRIPT_NYIAKENG_PUACHUE_HMONG, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOgham_Regular_otf, "Noto Sans Ogham Regular", UCDN_SCRIPT_OGHAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldHungarian_Regular_otf, "Noto Sans Old Hungarian Regular", UCDN_SCRIPT_OLD_HUNGARIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldItalic_Regular_otf, "Noto Sans Old Italic Regular", UCDN_SCRIPT_OLD_ITALIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldNorthArabian_Regular_otf, "Noto Sans Old North Arabian Regular", UCDN_SCRIPT_OLD_NORTH_ARABIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldPermic_Regular_otf, "Noto Sans Old Permic Regular", UCDN_SCRIPT_OLD_PERMIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldPersian_Regular_otf, "Noto Sans Old Persian Regular", UCDN_SCRIPT_OLD_PERSIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldSogdian_Regular_otf, "Noto Sans Old Sogdian Regular", UCDN_SCRIPT_OLD_SOGDIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldSouthArabian_Regular_otf, "Noto Sans Old South Arabian Regular", UCDN_SCRIPT_OLD_SOUTH_ARABIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOldTurkic_Regular_otf, "Noto Sans Old Turkic Regular", UCDN_SCRIPT_OLD_TURKIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOlChiki_Regular_otf, "Noto Sans Ol Chiki Regular", UCDN_SCRIPT_OL_CHIKI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOriya_Regular_otf, "Noto Sans Oriya Regular", UCDN_SCRIPT_ORIYA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOsage_Regular_otf, "Noto Sans Osage Regular", UCDN_SCRIPT_OSAGE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansOsmanya_Regular_otf, "Noto Sans Osmanya Regular", UCDN_SCRIPT_OSMANYA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPahawhHmong_Regular_otf, "Noto Sans Pahawh Hmong Regular", UCDN_SCRIPT_PAHAWH_HMONG, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPalmyrene_Regular_otf, "Noto Sans Palmyrene Regular", UCDN_SCRIPT_PALMYRENE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPauCinHau_Regular_otf, "Noto Sans Pau Cin Hau Regular", UCDN_SCRIPT_PAU_CIN_HAU, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPhagsPa_Regular_otf, "Noto Sans Phags Pa Regular", UCDN_SCRIPT_PHAGS_PA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPhoenician_Regular_otf, "Noto Sans Phoenician Regular", UCDN_SCRIPT_PHOENICIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansPsalterPahlavi_Regular_otf, "Noto Sans PsalterPahlavi Regular", UCDN_SCRIPT_PSALTER_PAHLAVI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansRejang_Regular_otf, "Noto Sans Rejang Regular", UCDN_SCRIPT_REJANG, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansRunic_Regular_otf, "Noto Sans Runic Regular", UCDN_SCRIPT_RUNIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSamaritan_Regular_otf, "Noto Sans Samaritan Regular", UCDN_SCRIPT_SAMARITAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSaurashtra_Regular_otf, "Noto Sans Saurashtra Regular", UCDN_SCRIPT_SAURASHTRA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSharada_Regular_otf, "Noto Sans Sharada Regular", UCDN_SCRIPT_SHARADA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansShavian_Regular_otf, "Noto Sans Shavian Regular", UCDN_SCRIPT_SHAVIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSiddham_Regular_otf, "Noto Sans Siddham Regular", UCDN_SCRIPT_SIDDHAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifSinhala_Regular_otf, "Noto Serif Sinhala Regular", UCDN_SCRIPT_SINHALA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSogdian_Regular_otf, "Noto Sans Sogdian Regular", UCDN_SCRIPT_SOGDIAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSoraSompeng_Regular_otf, "Noto Sans SoraSompeng Regular", UCDN_SCRIPT_SORA_SOMPENG, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSoyombo_Regular_otf, "Noto Sans Soyombo Regular", UCDN_SCRIPT_SOYOMBO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSundanese_Regular_otf, "Noto Sans Sundanese Regular", UCDN_SCRIPT_SUNDANESE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSylotiNagri_Regular_otf, "Noto Sans Syloti Nagri Regular", UCDN_SCRIPT_SYLOTI_NAGRI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSyriac_Regular_otf, "Noto Sans Syriac Regular", UCDN_SCRIPT_SYRIAC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTagalog_Regular_otf, "Noto Sans Tagalog Regular", UCDN_SCRIPT_TAGALOG, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTagbanwa_Regular_otf, "Noto Sans Tagbanwa Regular", UCDN_SCRIPT_TAGBANWA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTaiLe_Regular_otf, "Noto Sans TaiLe Regular", UCDN_SCRIPT_TAI_LE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTaiTham_Regular_otf, "Noto Sans Tai Tham Regular", UCDN_SCRIPT_TAI_THAM, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTaiViet_Regular_otf, "Noto Sans Tai Viet Regular", UCDN_SCRIPT_TAI_VIET, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTakri_Regular_otf, "Noto Sans Takri Regular", UCDN_SCRIPT_TAKRI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifTamil_Regular_otf, "Noto Serif Tamil Regular", UCDN_SCRIPT_TAMIL, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifTelugu_Regular_otf, "Noto Serif Telugu Regular", UCDN_SCRIPT_TELUGU, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansThaana_Regular_otf, "Noto Sans Thaana Regular", UCDN_SCRIPT_THAANA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifThai_Regular_otf, "Noto Serif Thai Regular", UCDN_SCRIPT_THAI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifTibetan_Regular_otf, "Noto Serif Tibetan Regular", UCDN_SCRIPT_TIBETAN, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTifinagh_Regular_otf, "Noto Sans Tifinagh Regular", UCDN_SCRIPT_TIFINAGH, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansTirhuta_Regular_otf, "Noto Sans Tirhuta Regular", UCDN_SCRIPT_TIRHUTA, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansUgaritic_Regular_otf, "Noto Sans Ugaritic Regular", UCDN_SCRIPT_UGARITIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansVai_Regular_otf, "Noto Sans Vai Regular", UCDN_SCRIPT_VAI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansWancho_Regular_otf, "Noto Sans Wancho Regular", UCDN_SCRIPT_WANCHO, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansWarangCiti_Regular_otf, "Noto Sans Warang Citi Regular", UCDN_SCRIPT_WARANG_CITI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSerifYezidi_Regular_otf, "Noto Serif Yezidi Regular", UCDN_SCRIPT_YEZIDI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansYi_Regular_otf, "Noto Sans Yi Regular", UCDN_SCRIPT_YI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansZanabazarSquare_Regular_otf, "Noto Sans Zanabazar Square Regular", UCDN_SCRIPT_ZANABAZAR_SQUARE, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)

#if NOTO_TANGUT
FONT (noto, NotoSerifTangut_Regular_otf, "Noto Serif Tangut Regular", UCDN_SCRIPT_TANGUT, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR);
#endif

EMPTY(UCDN_SCRIPT_CHORASMIAN)
EMPTY(UCDN_SCRIPT_CYPRO_MINOAN)
EMPTY(UCDN_SCRIPT_DIVES_AKURU)
EMPTY(UCDN_SCRIPT_KHITAN_SMALL_SCRIPT)
EMPTY(UCDN_SCRIPT_MAKASAR)
EMPTY(UCDN_SCRIPT_NANDINAGARI)
EMPTY(UCDN_SCRIPT_OLD_UYGHUR)
EMPTY(UCDN_SCRIPT_TOTO)
EMPTY(UCDN_SCRIPT_VITHKUQI)
EMPTY(UCDN_SCRIPT_SIGNWRITING)
EMPTY(UCDN_SCRIPT_TANGSA)

#ifndef TOFU_SYMBOL
FONT (noto, NotoSansMath_Regular_otf, "Noto Sans Math Regular", MUPDF_SCRIPT_MATH, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoMusic_Regular_otf, "Noto Music Regular", MUPDF_SCRIPT_MUSIC, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSymbols_Regular_otf, "Noto Sans Symbols", MUPDF_SCRIPT_SYMBOLS, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoSansSymbols2_Regular_otf, "Noto Sans Symbols2", MUPDF_SCRIPT_SYMBOLS2, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
FONT (noto, NotoEmoji_Regular_ttf, "Noto Emoji Regular", MUPDF_SCRIPT_EMOJI, FZ_LANG_UNSET, ANY_ORDER, NO_SUBFONT, REGULAR)
#endif

#ifndef TOFU_CJK
#ifndef TOFU_CJK_EXT
#ifndef TOFU_CJK_LANG
FONT (han, SourceHanSerif_Regular_ttc, "Source Han Serif Regular", MUPDF_SCRIPT_CJKV, CJKV_LANG, FZ_ADOBE_JAPAN, 0, REGULAR)
FONT (han, SourceHanSerif_Regular_ttc, "Source Han Serif Regular", MUPDF_SCRIPT_CJKV, CJKV_LANG, FZ_ADOBE_KOREA, 1, REGULAR)
FONT (han, SourceHanSerif_Regular_ttc, "Source Han Serif Regular", MUPDF_SCRIPT_CJKV, CJKV_LANG, FZ_ADOBE_GB, 2, REGULAR)
FONT (han, SourceHanSerif_Regular_ttc, "Source Han Serif Regular", MUPDF_SCRIPT_CJKV, CJKV_LANG, ANY_ORDER /*FZ_ADOBE_CNS*/, 3, REGULAR)
#else
FONT (droid, DroidSansFallbackFull_ttf, "Droid Sans Fallback Full", MUPDF_SCRIPT_CJKV, FZ_LANG_UNSET, ANY_ORDER, 0, REGULAR)
#endif
#else
FONT (droid, DroidSansFallback_ttf, "Droid Sans Fallback", MUPDF_SCRIPT_CJKV, FZ_LANG_UNSET, ANY_ORDER, 0, REGULAR)
#endif
#endif

#endif /* TOFU_NOTO */
